services:
  postgres:
    image: postgres:14.15-alpine3.21
    container_name: postgres
    env_file: db.env
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9999:9999"
    depends_on:
      - postgres
    env_file: app.env
    command:
      - java -jar app.jar