spring.datasource.url=${POSTGRES_LOGS_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver=org.postgresql.Driver

server.port=8080

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.mvc.format.date-time=iso

salary=150

spring.kafka.bootstrap-servers=http://localhost:9092
spring.kafka.consumer.group-id=messages_group
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false