spring.datasource.url=${POSTGRES_BUSES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver=org.postgresql.Driver

server.port=9999

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

spring.kafka.bootstrap-servers=http://localhost:9092
spring.kafka.consumer.group-id=messages_group
spring.kafka.producer.properties.spring.json.add.type.headers=false